### ISSUE TITLE
pre-commit overwrite setting

### ISSUE THREAD

**Issue by smichaud** [asottile/reorder_python_imports#107]
Maybe I did not find it in your/pre-commit doc, but is it possible to prevent pre-commit to fail and simply rewrite the files silently?

I currently have to commit, it fails, then I commit the files again, which becomes annoying.

Thank you.

**Comment by asottile** [comment]
pre-commit will never touch the staging area -- that's a good way to blindly commit unvetted code due to a malicious / buggy tool

there's an issue with a bunch of links to it but I'm on my phone so hope the tl;dr is good enough!

worst case you can always run `git add -u && !!` if you're ok firing from the hip
