### ISSUE TITLE
Work with python expressions during the reordering

### ISSUE THREAD

**Issue by mitzkia** [asottile/reorder_python_imports#72]
Hi Anthony, 

Sorry about that maybe the title description is not the best, we can rewrite it if needed.
My usecase is to reorder imports in a such file:
```
$ cat t.py 
import logging
logger = logging.getLogger("test")
import os
```

isort can deal with this and I like this way of reordering:
```
$ isort --diff t.py 
--- /tmp/t.py:before	2019-03-12 19:07:53.216402
+++ /tmp/t.py:after	2019-03-12 19:08:11.611216
@@ -1,3 +1,4 @@
 import logging
+import os
+
 logger = logging.getLogger("test")
-import os
```

As I have checked `reorder_python_import` can not deal with such code (it stoppes at ` logger = logging.getLogger("test")` line), sorry if I've missed something from actual features.
My question is that, can it be a possible feature to handle with such code?
I have already read some previous issues and PRs where you said that it is very hard to do anything outside of imports. Maybe this is not the same case. Correct me if I am wrong.

Thanks

**Comment by asottile** [comment]
`reorder-python-imports` is [intentionally timid](https://github.com/asottile/reorder_python_imports#using--noreorder) and will never touch imports after code.  this is one of the direct reactions to the (imo unaccaptable) behaviour that `isort` has.  reordering intermixed code and imports breaks stuff all the time

So no, this won't happen -- and by design :)
