### ISSUE TITLE
Exit code 1 even when successful

### ISSUE THREAD

**Issue by brunns** [asottile/reorder_python_imports#74]
`reorder_python_imports` is returning a status code of 1 when it has found changes to be made, even when it's successful made those changes. This is inconvenient when scripting, because it's interpreted as a failure.

This behavior could be made optional. I'd be happy to put together a PR if it'll be welcome.

**Comment by asottile** [comment]
This is intentional, it is actually *for* scripting so one can tell when changes have been made or not.

I'd suggest you run `reorder-python-imports` via [pre-commit](https://pre-commit.com) fwiw

**Comment by brunns** [comment]
Fair enough - it's your tool! 

FWIW, I run this kind of stuff via tox, so the approach [black](https://github.com/ambv/black) takes fits my workflow better.

**Comment by asottile** [comment]
[you can use `pre-commit` in tox as well](https://github.com/asottile/reorder_python_imports/blob/e27d33e9fe7764512c17a7ce6dac1d2b04700dd3/tox.ini#L12) which black also [suggests / supports](https://github.com/ambv/black#version-control-integration)

**Comment by brunns** [comment]
Thanks.

**Comment by antonagestam** [comment]
I agree with @brunns here. Returning an exit code of 1 would only make sense when checking if a file is adhering to the scheme or not. When formatting code, an exit code of 1 rather indicates that the program wasn't able to format the file.

This behavior makes this program really unpleasant as an external tool in PyCharm on its own, since it will open an output dialog on every invocation that changes a file. For me it's not that interesting if the tool changed the file or not, I will notice that when checking in my code in source control. It's only interesting if the tool **would** change the code when building automated checks in CI, but reorder-python-imports provides no facilities for that and instead forces me to count the lines of the output of `--diff`. 

I'd be really happy if you would reconsider your stance here and make the tool more usable on its own.

That said, cheers, and thank you for the really solid work you put into this project!

**Comment by antonagestam** [comment]
I made a tiny CLI wrapper around reorder-python-imports that works the way I want it to: https://github.com/antonagestam/sorti

**Comment by asottile** [comment]
#82
